"""Add Bazzix Credits Phase 1A tables

Revision ID: 78a60373f321
Revises: 320fb6ffaf0e
Create Date: 2026-09-17 20:11:55.803548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a60373f321'
down_revision: Union[str, Sequence[str], None] = '320fb6ffaf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_balance', sa.Integer(), nullable=False),
    sa.Column('purchased_balance', sa.Integer(), nullable=False),
    sa.Column('reserved_balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('ai_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_request_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_source', sa.Enum('PROVIDER', 'ESTIMATED_PARTIAL', name='usage_source_enum'), nullable=True),
    sa.Column('provider_cost', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'PARTIAL', 'FAILED', name='request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_request_id', name='uq_user_client_request')
    )
    op.create_index(op.f('ix_ai_request_logs_client_request_id'), 'ai_request_logs', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_id'), 'ai_request_logs', ['id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('RESERVATION', 'CHARGE', 'REFUND', 'SIGNUP_BONUS', 'PURCHASE', 'ADJUSTMENT', name='transaction_type_enum'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_id'), 'ledger_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_ai_request_logs_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_client_request_id'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
