"""add updated_at to ai_request_logs

Revision ID: b0d80f7e5795
Revises: c4a6eddc75b3
Create Date: 2026-09-18 13:27:55.802504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d80f7e5795'
down_revision: Union[str, Sequence[str], None] = 'c4a6eddc75b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_request_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_request_logs', 'updated_at')
    # ### end Alembic commands ###
